### ISSUE TITLE
Feature Request: Add NAT modeling within this plugin as well

### ISSUE THREAD

**Issue by FragmentedPacket** [nautobot/nautobot-plugin-firewall-models#22]
### Environment
* Nautobot version:  
* nautobot-plugin-firewall-model version:  

### Proposed Functionality
It would be great to model NAT more extensibly within this plugin. The current NAT and the incoming change to NAT to allow 1:many within Nautobot core (https://github.com/nautobot/nautobot/issues/630) should suffice for a lot of uses cases, but doesn't cover PAT. I discussed with @lampwins about this and a lot of the models required to model NAT/PAT more extensibly already exists within this plugin.

### Use Case
Model NAT/PAT to be able to track and configure on firewalls.

**Comment by scetron** [comment]
@davidmclintock Is interested in tracking PAT as well.

**Comment by Kircheneer** [comment]
# NAT Model Proposition

This should be able to cover
- DNAT
- SNAT
- PAT
for all the use cases I was able to think of.

Similar to the pattern for `Any` in the `AddressObject` and `ServiceObject` realm `None` means no change in this case.

## Model

I want to introduce two new models to this plugin, `NATPolicy` as an equivalent to `Policy` and `NATPolicyRule` as an equivalent to `PolicyRule`:

- `NATPolicy` should have all the fields that `Policy` has, just with `nat_rules` instead of `policy_rules`
- `NATPolicyRule` should have all the fields that `PolicyRule` has, except that all the following fields are duplicated for before/after...
  - `source_service`
  - `source_service_group`
  - `destination_service`
  - `destination_service_group`
  - `source_address`
  - `source_address_group`
  - `destination_address`
  - `destination_address_group`
- ...and the following fields are removed
  - `action`
- For the `AddressObject` instances that can go into those `NATRule` fields, forbid `FQDN` type objects?

## Example JSON

The following are quick example JSON files of only those fields that changed in comparison to the non-NAT models and are interesting to the specific example.

### Example 1

This model describes a NAT policy that

- PATs the source IP address behind 10.10.10.10/32

```json
{
  "nat_policies":
  {
    "nat_rules": [
      {
        "source_service_before": null,
        "source_service_after": null,
        "destination_service_before": null,
        "destination_service_after": null,
        "source_before": "10.0.0.0/24",
        "source_after": "10.10.10.10/32",
        "destination_before": null,
        "destination_after": null
      }
    ]
  }
}
```

### Example 2

This model describes a NAT policy that

- DNATs the destination IP address from 1.1.1.1 to 172.16.1.1
- Swaps the destination port of 80/TCP with 8080/TCP

```json
{
  "nat_policies":
  {
    "nat_rules": [
      {
        "source_service_before": null,
        "source_service_after": null,
        "destination_service_before": "80/TCP",
        "destination_service_after": "8080/TCP",
        "source_before": null,
        "source_after": null,
        "destination_before": "1.1.1.1/32",
        "destination_after": "172.16.1.1/32"
      }
    ]
  }
}
```

### Example 3

This model describes a NAT policy that

- PATs the source IP addresses from a group behind 10.10.10.10/32

```json
{
  "nat_policies":
  {
    "nat_rules": [
      {
        "source_service_before": null,
        "source_service_after": null,
        "destination_service_before": "80/TCP",
        "destination_service_after": "8080/TCP",
        "source_group_before": "Internal_Network (FK to AddressObjectGroup)",
        "source_group_after": "1.1.1.1/32",
        "destination_before": null,
        "destination_after": null
      }
    ]
  }
}
```

## Open questions

- [ ] Do use cases exist that warrant explicitly changing a source port?
  - This is specifically interesting, because for the use case of many (private) source addresses mapping to few (public) source addresses the source port is implicitly changed, omitting the `source_service` field family could make this clearer
- [ ] Is there a point in having the `ServiceGroup` field families? I imagine if you will do a destination port translation, then only 1-to-1
- [ ] Do we want a mode field to distinguish between static mappings and dynamic mappings? Probably this can be deduced from comparing the before/after counts, but then sometimes maybe you want the mapping to be random?

Happy to hear your thoughts.

**Comment by nkallergis** [comment]
Some random thoughts...

**On point 1 (source port)**
Even though I cannot think of a specific use case, most (all?) vendors do support this feature. Also, to bind this with your third point about modes, in Cisco configuration this specific use-case is called "overload".

**On point 2 (ServiceGroup)**
I've seen this used multiple times as a filter of sorts. You add an original service to tell the firewall to perform NAT only if the requests is towards a specific set of ports. These ports remain un-translated.

**Comment by whitej6** [comment]
Thoughts on using `original_src` and `translated_src` pattern for the attr names over before/after?

**Comment by ozmusic** [comment]
@Kircheneer looking at example 2 and destination_after, is there scope in that for destination_after to be a list or is this covered by an address object group?
Something that would be nice to see as well is the addition of a healthcheck field, we could handle that with a custom field for a basic version as the model for a healthcheck may be scope creep here.

**Comment by Kircheneer** [comment]
@whitej6 I believe this can be closed as the feature is implemented.

**Comment by ozmusic** [comment]
@Kircheneer the permissions for the demo user need to be updated to include the nat policies, I'll upgrade our lab instance and check it out there :)

**Comment by whitej6** [comment]
@nniehoff we beed to update permissions for demo
